trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build and Package Application'
        steps:
          - checkout: self

          - task: JavaToolInstaller@0
            displayName: 'Set Up Java'
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
              
          - script: mvn clean package
            displayName: 'Build Application'

          - script: mv target/*.jar target/bankapp.jar
            displayName: 'Rename JAR for Consistency'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              pathToPublish: 'target/bankapp.jar'
              artifactName: 'drop'

  - stage: DockerBuildPush
    displayName: 'Docker Build & Push'
    dependsOn: Build
    jobs:
      - job: DockerJob
        displayName: 'Build & Push Docker Image'
        steps:
          - checkout: self

          - script: |
              echo "Validating Docker Hub credentials..."
              if [[ -z "$(DOCKER_HUB_USERNAME)" || -z "$(DOCKER_HUB_PASSWORD)" ]]; then
                echo "ERROR: Docker Hub credentials are not set!"
                exit 1
              fi
            displayName: 'Validate Credentials'

          - script: |
              docker build -t $(DOCKER_HUB_USERNAME)/bankapp:latest .
            displayName: 'Build Docker Image'

          - script: |
              echo $(DOCKER_HUB_PASSWORD) | docker login -u $(DOCKER_HUB_USERNAME) --password-stdin
            displayName: 'Log in to Docker Hub'

          - script: |
              docker push $(DOCKER_HUB_USERNAME)/bankapp:latest
            displayName: 'Push Docker Image to Docker Hub'
