name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/aws-key.pem
          chmod 600 ~/.ssh/aws-key.pem
          ls -lah ~/.ssh  # Verify directory and permissions
          head -n 5 ~/.ssh/aws-key.pem  # Verify key presence (Partial Output)

      - name: Debug EC2 Host
        run: echo "EC2 Host: ${{ secrets.AWS_EC2_HOST }}"

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/aws-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_EC2_HOST }} "echo '✅ SSH Connection Successful!'"
        continue-on-error: true  # Prevents immediate failure, allowing debugging

      - name: Deploy JAR File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          source: "target/bankapp.jar"
          target: "/home/ubuntu/app/"

      - name: Restart Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart bankapp.service
            sudo systemctl status bankapp.service --no-pager
